M48
; DRILL file {KiCad 9.0.2} date 2025-11-16T13:07:26+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-16T13:07:26+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
%
G90
G05
T1
X94.82Y-76.22
X94.82Y-82.0
T2
X89.734Y-71.608
X90.75Y-76.688
X91.766Y-71.608
M30
